// Code generated by Slice Machine. DO NOT EDIT.

import Contact from './Contact';
import HeroSlice from './HeroSlice';
import MainNavSlice from './MainNavSlice';

export {
	Contact,
	HeroSlice,
	MainNavSlice,
};

export const components = {
	contact: Contact,
	hero_slice: HeroSlice,
	main_nav_slice: MainNavSlice,
};
